import { addProject, expect, newTask, openProject, pickModel, sidebar, test } from "../fixtures.js";

test("prompt actions require text and pinned prompts spawn independent tasks", async ({ page, agenttik }) => {
  await addProject(page);
  await openProject(page);
  await newTask(page);
  await pickModel(page);
  const box = page.getByPlaceholder("Ask the agent…");
  const more = page.getByRole("button", { name: "More prompt actions" });
  const primary = page.locator('.prompt-bar button[type="submit"]');
  await expect(primary).toBeDisabled();
  await expect(more).toBeDisabled();
  await box.fill("   ");
  await expect(primary).toBeDisabled();
  await box.fill("x");
  await expect(primary).toBeEnabled();
  await expect(more).toBeEnabled();
  await box.fill("Reusable prompt");
  await more.click();
  await page.getByRole("button", { name: "Pinned task", exact: true }).click();
  const editor = page.getByRole("textbox", { name: "Pinned prompt", exact: true });
  await expect(editor).toHaveValue("Reusable prompt");
  const pins = async () => (await page.request.get(agenttik.url + "/api/schedules?window=all")).json();
  const pin = (await pins())[0];
  const detail = async () => (await page.request.get(agenttik.url + `/api/schedules/${pin.id}`)).json();
  expect((await detail()).runs).toHaveLength(0);
  expect(pin.next_run_at).toBe(0);
  await editor.fill("discard this");
  await page.getByRole("button", { name: "Discard", exact: true }).click();
  await expect(editor).toHaveValue("Reusable prompt");
  await editor.fill("Saved change");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect.poll(async () => (await detail()).schedule.prompt).toBe("Saved change");
  await page.reload();
  await expect(editor).toHaveValue("Saved change");
  const playedResponse = page.waitForResponse(r => r.url().endsWith(`/api/schedules/${pin.id}/run`) && r.request().method() === "POST");
  await sidebar(page).getByRole("button", { name: "Play pinned task" }).click();
  const played = await (await playedResponse).json();
  await expect(page.getByPlaceholder("Ask the agent…")).toBeVisible();
  await expect(sidebar(page).getByText("Reusable prompt", { exact: true })).toBeVisible();
  await sidebar(page).getByText("Reusable prompt", { exact: true }).click();
  await page.getByRole("button", { name: "Customize and run…", exact: true }).click();
  const custom = page.getByRole("textbox", { name: "One-off prompt" });
  await expect(custom).toHaveValue("Saved change");
  await custom.fill("");
  await expect(page.getByRole("dialog").getByRole("button", { name: "Send", exact: true })).toBeDisabled();
  await custom.fill("One-off change");
  const response = page.waitForResponse(r => r.url().endsWith(`/api/schedules/${pin.id}/run`) && r.request().method() === "POST");
  await page.getByRole("dialog").getByRole("button", { name: "Send", exact: true }).click();
  const spawned = await (await response).json();
  expect(spawned.schedule_id).toBe(0);
  expect(spawned.id).not.toBe(played.id);
  for (const [id, prompt] of [[played.id, "Saved change"], [spawned.id, "One-off change"]]) {
    const task = await (await page.request.get(`${agenttik.url}/api/sessions/${id}`)).json();
    expect(task.messages.filter(m => m.role === "user").map(m => m.content)).toEqual([prompt]);
    expect(task.session.done_at).toBe(0);
  }
  expect((await detail()).schedule.prompt).toBe("Saved change");
  expect((await detail()).runs).toHaveLength(0);
  await expect(page.getByPlaceholder("Ask the agent…")).toBeVisible();
});
